Event.create!(name: "Wedding", location: "Boston", date: "Aug-01-2025")
Event.create!(name: "Charity", location: "L.A", date: "Jun-18-2026")
Event.create!(name: "Gala", location: "New York", date: "may-03-2027")

Attendee.create!(name: "Peter", email: "peter@email.com")
Attendee.create!(name: "Kate", email: "kate@email.com")
Attendee.create!(name: "Sophia", email: "sophia@email.com")
Attendee.create!(name: "Logan", email: "logan@emial.com")
Attendee.create!(name: "John", email: "john@email.com")
Attendee.create!(name: "Christy", email: "christy@email.com")

Registration.create!(attendee_id: 1, event_id: 1)
Registration.create!(attendee_id: 2, event_id: 1)
Registration.create!(attendee_id: 3, event_id: 2)
Registration.create!(attendee_id: 4, event_id: 2)
Registration.create!(attendee_id: 5, event_id: 3)
Registration.create!(attendee_id: 6, event_id: 3)
